<?php

namespace AppBundle\Repository;

/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends \Doctrine\ORM\EntityRepository
{

    public function getFichesAValiderById($id)
    {
        $query = $this->createQueryBuilder('f')
            ->where('f.idVisiteur = :id')
            ->innerJoin('f.Etat', 'e')
            ->innerJoin('f.idVisiteur', 'v')
            ->andWhere("f.Etat != 'va'")
            ->select('f, e, v')
            ->orderBy('f.mois', 'DESC')
        ->setParameters(['id' => $id]);
        return $query->getQuery();
    }

}
