<?php

namespace UserBundle\Repository;
use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getVisiteurs()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('v')
            ->from(User::class, 'v')
            ->innerJoin('v.groupe', 'g')
            ->where("g.libelle = 'visiteur'")->getQuery();
    }

}
